version: 0.0
os: linux
files:
  - source: /
    destination: /web/
hooks:
  BeforeInstall:
    - location: scripts/code_deploy_before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/code_deploy_application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/code_deploy_application_stop.sh
      timeout: 300
      runas: root
