version: 0.2

phases:
  install:
    commands:
        - python3 -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/code_deploy_application_start.sh
    - scripts/code_deploy_application_stop.sh
    - scripts/code_deploy_before_install.sh
